lo:
  hostname: liveobjects.orange-business.com
  api-key:
  topic:
  synchronization-interval: 60000
  message-qos: 1
  mqtt-persistence-dir: ${basedir:.}/temp/
  keep-alive-interval-seconds: 30
  connection-timeout: 30000
  message-batch-size: 10

aws:
  sqs:
    queue-url:
    thread-pool-size: 40
    connection-timeout: 5000
    task-queue-size: 150000
    throttling-delay: 5000
    max-send-attempts: 3

